### ISSUE TITLE
Climate entity error: this entity is unavailable

### ISSUE THREAD

**Issue by saragrigolin** [vincentwolsink/home_assistant_micronova_agua_iot#72]
Hi everyone,
In the last days I'm having some problems with this integration. The climate entity is unavailable but the new sensors seems to work fine.
I have a Ravelli stove, I'm running v0.2.4 of Micronova Agua IOT integration and I tried to remove and add the pellet stove again and again a lot of times. 

Could the cause of the problem be that the stove is off and I haven't turned it on yet since I reinstalled the integration a few days ago? It seems strange to me because the climate entity has always been available even during the summer when the stove was off.

Here's the logs:
```
2023-10-19 00:35:38.171 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform aguaiot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 316, in state_attributes
    hass, self.current_temperature, temperature_unit, precision
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aguaiot/climate.py", line 208, in current_temperature
    return self._device.get_register_value(self._temperature_get_key)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AguaIOTHeatingDevice' object has no attribute '_temperature_get_key'
2023-10-19 00:35:38.192 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

``` 

<img width="599" alt="Screenshot 2023-10-19 at 00 40 47" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/56165909/38cc6eaf-a701-41b2-89ca-605a8f1fb5f8">
<img width="344" alt="Screenshot 2023-10-19 at 00 40 56" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/56165909/e5b09e9f-e062-45e5-a845-3d1c8152c761">

**Comment by saragrigolin** [comment]
@vincentwolsink here's the diagnostic file: [Home Assistant Config Entry.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13039460/Home.Assistant.Config.Entry.json.txt). Honestly I don't know why in the file the aguaiot version is 0.2.1 when on HACS I see that I don't have updates and the last installed version is 0.2.4.
